export enum NotificationType {
  TICKET_CREATED = 'TICKET_CREATED',
  TICKET_ASSIGNED = 'TICKET_ASSIGNED',
  TICKET_STATUS_CHANGED = 'TICKET_STATUS_CHANGED',
  TICKET_COMMENTED = 'TICKET_COMMENTED',
  TICKET_SLA_BREACHED = 'TICKET_SLA_BREACHED',
}
